logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

execution:
  durable: false

execution_engine: asyncio
logger:
  transports: [console, file]
  level: debug
  progress_display: true

openai:
  default_model: gpt-4o

mcp:
  servers:
    dark_forest:
      transport: "sse"
      url: "http://games-0upq:10000/sse"
      description: "A remote MCP server that allows you to interact with the Dark Forest video game, getting information about your Dark Forest player and make moves in the game."
    solana:
      transport: "sse"
      url: "http://solana-mcp-otfo:10000/sse"
      description: "A remote MCP server that allows you to interact with the Solana blockchain, getting information from it and interacting with it."